### ISSUE TITLE
Feature Request: Add gtfs2graph support

### ISSUE THREAD

**Issue by lolpro11** [rust-transit/gtfs-to-geojson#15]
There are some missing fields in this gtfs-to-geojson lib, compared to the C++ version of gtfs2graph. Now I know that these fields are technically optional, but I would like them for support for graph analysis.	
deg: "2"
deg_in: "2"
deg_out: "2"
id: "0x5ac485b09c50"
also, color is in the form of `rgb(255,255,255)`. I think we should have it be something like: `FFFFFF`. This allows for interoperability with C++ tools.
Edit: 
Seems to also be missing fields of "not connected to" along with not splitting linestrings.

**Comment by Tristramg** [comment]
Hello,
I don’t think this project is suited nor will ever be to work on graph representation on a transit network.

This is only meant for to extract the geometries from the gtfs to render them on a map as geojson. Nothing more.

**Comment by kylerchin** [comment]
Agreed, this is not a graph analysis library. This crate should stay narrow in purpose.
